### ISSUE TITLE
More information on Discord bot required permitions

### ISSUE THREAD

**Issue by WolfangT** [camyosh/tablestuck#19]
Installed and ran the bot on a linux server, but i have never installed  or used a discord bot before and i am unsure of which permissions will the bot need, i assume send messages, but i don't know if it will need to manage roles, use emojis, etc..

**Comment by DocZane** [comment]
for the moment, the best thing to do is to give your bot moderator permissions (code 8 for the invite link), mostly since we are adding new functionalities all the time and we aren't sure what permissions we might need next. when we're all done, We'll make sure we have a link with only the exact permissions the bot needs.
